### ISSUE TITLE
How about candidate images?

### ISSUE THREAD

**Issue by AdoraNwodo** [adorahack/istandwithyou-api#3]
@iamfunsho I apologize for adding an avatar URL field. But referring to [figma](https://www.figma.com/file/DDNorOpAze0UU5IEVic4Qf4c/Untitled?node-id=1%3A13), each candidate should have an image.

My suggestion is to get the images in a directory in the Lumen api and refer to them instead of uploading images (there's no dashboard). 
So I'm guessing `$request->only(['name', 'party']);` can become this `$request->only(['name', 'party', 'avatar']);` (with an avatar field existing in the DB) ?

**Comment by devfunsho** [comment]
I think we can dynamically do this on the front end, you can save the images in your **asset** folder using the **candidate_id** as the name. This will reduce the workload on the server, not the ideal approach, but I believe is the best in this scenario.

**Comment by AdoraNwodo** [comment]
Okay, I don't fully understand but let's take this conversation to Whatsapp. So that we can talk extensively.
